### PR TITLE
Add publications collection.

### PR DESCRIPTION
**Pull request by jrper**
As discussed in the dev meeting, this proposal adds a Jekyll collection for publications to the website, to be populated with papers. The process to add a paper is: create a new file in _publications with a title like 2016-01-06-MyNewPaper.md and containing a code block like 

```

---
title:  "An improved quantitative measure of the tendency for volcanic ash plumes to form in water:     implications for the deposition of marine ash beds"
authors: C. T. Jacobs, T. J. Goldin, G. S. Collins, M. D. Piggott, S. C. Kramer, H. J. Melosh, C. R. G.  Wilson, P. A. Allison
journal: Journal of Volcanology and Geothermal Research
doi: 10.1016/j.jvolgeores.2014.10.015
date: 1/2015
volume: 290
pages: 114-124

---
```

### CODE REVIEW

**Comment by wence-** [comment]
FWIW, if you want a bibtex-based solution instead, we use bibbase (bibbase.org).

**Comment by ctjacobs** [comment]
So experience tells me that, just like the old AMCG wiki publications page, this will eventually be forgotten and just go stale. Can we not just link to: https://www.imperial.ac.uk/engineering/departments/earth-science/research/research-groups/amcg/publications/ which automagically updates?

**Comment by jrper** [comment]
No, because Fluidity != AMCG.

Also the magic for that page isn't very good.

**Comment by ctjacobs** [comment]
Ok. The script in `publications.html` isn't looping over the files in `_publications` locally here - assuming this gets fixed I'm fine with this going in. But if someone is willing to invest the time to integrate bibbase then I'd prefer that since it makes it much easier to import references.

**Comment by wence-** [comment]
bibbase integration is a one-liner:

```
<script src="http://www.bibbase.org/show?bib=URL_TO_YOUR_BIBFILE&jsonp=1"></script>
```

**Comment by ctjacobs** [comment]
Done - thanks Lawrence. Works fine locally when pointing it to the Firedrake team's .bib file, so I assume it will work fine once the link to the Fluidity .bib file becomes live.

**Comment by ctjacobs** [comment]
And it does indeed work.

**Comment by jrper** [comment]
Great, what's the process to update?

**Comment by wence-** [comment]
Add bibtex entry to `publications/publications.bib` and push.  The publications page is generated on-the-fly via some javascript magic.

**Pull request merged**
